### ISSUE TITLE
Crashed Admin

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#126]
Initially the DCLP board appeared very nicely.

I had added some members to the DCLP board. Went well. Added decrees. Also went well.
Wanted to "create" an email message. And got a

We're sorry, but something went wrong.
We've been notified about this issue and we'll take a look at it shortly.

You should be redirected momentarily.

Admin seems to have crashed. I cannot view any of the boards now. all return the SoSOL 500 error.

DCLP board now not showing up any more. Seem to have crashed something. Other boards are showing (checked HGV, DDbDP)

**Comment by ryanfb** [comment]
The problem was a "subject" field was added to the Emailer model (https://github.com/sosol/sosol/commit/7a028a0788f6e4c6fab0f29f750ee31fb1c2f6a9) between the previous deploy on Dev and now. I thought I had run the Rails migrations before deploying, but apparently I neglected to run them with `RAILS_ENV="proudction"`, so the field was missing, resulting in this error when you tried to work with the Emailers.

I brought down the dev editor, ran the migrations, and brought it back up, so this issue should be fixed  now.
