### ISSUE TITLE
Entered text is at present lost

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#233]
http://papyri.info/editor/publications/54260/ddb_identifiers/123511/editxml

has no content. 

I renamed 
https://github.com/papyri/idp.data/blame/master/DDB_EpiDoc_XML/p.oxy/p.oxy.3/p.oxy.3.521.xml
to 
https://github.com/papyri/idp.data/blame/master/DDB_EpiDoc_XML/p.oxy/p.oxy.3/p.oxy.3.521r.xml
and changed idnos
I did this all in github.
https://github.com/papyri/idp.data/commit/c3134d975527ee9cd9bf9c3f78378757236ac1c1

This meant that the editor could no longer identify in master anything that corresponded to its copy of 
https://github.com/papyri/idp.data/blame/master/DDB_EpiDoc_XML/p.oxy/p.oxy.3/p.oxy.3.521.xml 
I could not rename the file and as a result of the attempt the entered text is no longer available.

The XML of 
http://papyri.info/editor/publications/54260/ddb_identifiers/123511/editxml
is empty

I reinstated a copy of
https://github.com/papyri/idp.data/blame/master/DDB_EpiDoc_XML/p.oxy/p.oxy.3/p.oxy.3.521.xml
with
https://github.com/papyri/idp.data/commit/a3705158c2c5aeb127c30a4f39585e0c27d7fe78

I hoped that this would allow the text to reappear in 

 - [ ] http://papyri.info/editor/publications/54260/ddb_identifiers/123511/editxml

It does not.

Would you please try to reinstate the text entered originally at 
http://papyri.info/editor/publications/41666
where I see that the entered text is also no longer visible:
http://papyri.info/editor/publications/41666/ddb_identifiers/94568/editxml

Thanks and sorry about the mess. I should really have forseen this problem and acted differently.

**Comment by ryanfb** [comment]
I see a finalizer rename of the identifier to `papyri.info/ddbdp/pap.congr.26;;300` that succeeded in Git, but not in the database (it looks like this was caused by the board branch being missing for some reason which likely triggered an exception + rollback), so the database still thought the identifier was `papyri.info/ddbdp/p.oxy;3;521` and was looking for that file path.

I've rewound the finalizer/user branches to the commit before the `papyri.info/ddbdp/pap.congr.26;;300` rename & restored the board branch, so this should now be finalizable.
