### ISSUE TITLE
PE issue - Overview, Text, Meta tabs not working in Firefox

### ISSUE THREAD

**Issue by rla2118** [papyri/sosol#244]
The "Overview, Text, Meta" tabs don't work in either DDbDP or DCLP if one is using Firefox.

**Comment by hcayless** [comment]
This looks to me like the EOL for prototype.js has probably hit Firefox.

**Comment by jcowey** [comment]
Seems also to affect the Finalization button.

**Comment by ryanfb** [comment]
Just managed to check in Firefox, prototype 1.7.3 didn't fix it. @hcayless is working on switching these calls over to jQuery. FWIW, as a workaround, they still work in both Chrome and Safari.

**Comment by jcowey** [comment]
Thanks for the feedback. Safari works, wow! surprises me.

**Comment by hcayless** [comment]
Working on it...

**Comment by ryanfb** [comment]
Is anyone still seeing this in Firefox? It looks like it's working for me now in production.

Trying to work out what exactly fixed it, because I *do* still see the same behavior in an old branch I'm trying to revitalize to close out sosol/sosol#97…

**Comment by hcayless** [comment]
I fixed it a few weeks ago with a CSS tweak. Nothing to do with JavaScript at all :-D. I still want to go through and rip prototype out, but less urgency now.

**Comment by ryanfb** [comment]
I figured out the same thing while trying to work on the asset pipeline conversion. I *did* notice there's also a JS error caused by including prototype before jQuery, which should be fixed by https://github.com/sosol/sosol/commit/3e5729f364b2e23faed858afcecc3a038c38caa2, but I'm not sure it's breaking anything (that commit isn't in production yet).
