### ISSUE TITLE
Unusual behaviour

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#27]
Hello Ryan. I cannot remember having seen this behaviour before.

http://papyri.info/editor/publications/50795

works fine. 
http://papyri.info/editor/publications/50795/ddb_identifiers/115341/editxml
is empty
http://papyri.info/editor/publications/50795/ddb_identifiers/115341/edit
and
http://papyri.info/editor/publications/50795/ddb_identifiers/115341/preview
say

Die Seite papyri.info funktioniert nicht

papyri.info kann diese Anfrage momentan nicht verarbeiten.
500

Can you please make them available so that I can finalize them. Thanks

**Comment by ryanfb** [comment]
This is usually the behavior when a Git branch is broken (repo doesn't have all the objects for the branch). Eventually sosol/sosol#157 should at least notify you that this is what's going on instead of giving the generic error, but I probably also need to look into why this keeps happening.

To fix this one, I re-sent it to you as finalizer, which re-copied the branch: http://papyri.info/editor/publications/51256
