### ISSUE TITLE
Stuck File DDB Board

### ISSUE THREAD

**Issue by samosafuz** [papyri/sosol#327]
https://papyri.info/editor/publications/110578 is stuck on the DDB board without a finalizer, and the 'make me finalizer' button isn't dislodging it. Can you free it up and assign it to me (http://papyri.info/editor/users/Mike%20Sampson)?

**Comment by ryanfb** [comment]
I think this was caused by sosol/sosol#252. There was one commit that was made after submission that changes Ἑρμαυῶτος in line 3 to Ἑρμαουῶτος, which was causing "make me finalizer" to fail due to the way finalizer commit flattening works. I pulled that commit in to the board's copy of the branch and sent it to you for finalization.
