### ISSUE TITLE
Files not properly processed: Exceptionally strange

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#42]
This morning I voted Accept Straight to Finalization on T.Alb. 33. It has disappeared without trace on the editorial board as far as I can see.
I opened the history of my bookmarks for today's used sites and was able to find

 - [ ] http://papyri.info/editor/publications/52832/ddb_identifiers/120101/edit

Searching for that (or simply `papyri.info/editor/publications/52832`) I have returned to my screen: 
Publication not found

Would you please look into this and if possible assign the recovered file to me as finalizer
http://papyri.info/editor/users/james.cowey

Thanks

I really do not think that I hit the wrong "vote" but really selected Accept Straight to Finalization

**Comment by ryanfb** [comment]
I can't find any publication with "T.Alb. 33" in the title or branch, and I can't find 52832 in the logs. So I'm not sure what happened here.  The only thing I can think of is the "graffiti" vote action, which would explain why I can't find the original publication either (instead of just the board copy). Maybe we should have more guards around that, or set a flag instead of actually destroying the publication?
