### ISSUE TITLE
Really effing weird and worrying shit

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#52]
Two people finalized the same file!! 
http://papyri.info/editor/publications/53959
How did the file land in two different finalizing dashboards.
http://papyri.info/editor/users/james.cowey
 SB 28, 17015 (SB 28 17015)   Ready. November 04, 2016 15:11 

[† ἐν ὀνό]μ̣α̣τ̣ι̣ [τ]ῆ̣ς ἁγίας καὶ ζῳοποιοῦ καὶ ὁμοουσίου Τριάδος Πατρ̣ὸ̣[ς καὶ Υἱοῦ καὶ Ἁγίου Πνεύματος.]
[βασιλ]ε̣[ί]ας τοῦ̣ θ̣ει̣ο̣τ̣ά̣τ̣ο̣υ καὶ γαληνοτάτου καὶ θεοστεφοῦς ἡμῶν̣ [δεσπότου Φλ(αουίου) Ἡρακλείου τοῦ]
[αἰων]ίου Αὐγούστου Αὐτοκράτορος καὶ μεγίστου εὐεργ̣[έτου ἔτους - ca.2 - μετὰ τὴν ὑπατείαν τοῦ]
[αὐτο]ῦ εὐσεβεστάτου ἡμῶν δεσπότου ε  ̣(*)[ -ca.?- ]
-- -- -- -- -- -- -- -- -- --
Apparatus

^ 4. or ἔτ̣[ους], or Ἐπ̣[είφ], or ἐπ̣[αγομένων]

(captured before the second commit) came through

http://papyri.info/editor/users/berkes.lajos
 SB 28, 17015 (SB 28 17015)   ready November 07, 2016 14:00 

[ † ἐν ὀνό]μ̣α̣τ̣ι̣ [τ]ῆ̣ς ἁγίας καὶ ζῳοποιοῦ καὶ ὁμοουσίου Τριάδος Πατρ̣ὸ̣[ς καὶ Υἱοῦ καὶ Ἁγίου Πνεύματος.]
[βασιλ]ε̣[ί]ας τοῦ̣ θ̣ει̣ο̣τ̣ά̣τ̣ο̣υ καὶ γαληνοτάτου καὶ θεοστεφοῦς ἡμῶν̣ [δεσπότου Φλ(αουίου) Ἡρακλείου τοῦ]
[αἰων]ίου Αὐγούστου Αὐτοκράτορος καὶ μεγίστου εὐεργ̣[έτου ἔτους -ca.?- μετὰ τὴν ὑπατείαν τοῦ]
[αὐτο]ῦ εὐσεβεστάτου ἡμῶν δεσπότου ἔτ̣[ους](*)  ̣[ -ca.?- ]
-- -- -- -- -- -- -- -- -- --
Apparatus

^ 4. or Ἐπ̣[είφ], or ἐπ̣[αγομένων]

I do not remember there having been a problem with voting or with make me finalizer. If that memory is correct, then it is worrying that the same file landed/stayed on two different finalizing dashboards.
Obviously the second commit overwrites the previous one. I thought that this would be no problem as one can simply go back a commit. The second commit:
https://github.com/papyri/idp.data/commit/05b77fd39d32b0a83142c24fb3ecd123357f117d
is still preserved in 
https://github.com/papyri/idp.data/blame/master/DDB_EpiDoc_XML/sb/sb.28/sb.28.17015.xml
the first commit is no longer there
In the second commit a mistake was made in that it was not renamed:
https://github.com/papyri/idp.data/blame/master/DDB_EpiDoc_XML/sb/sb.28/sb.28.17015.xml#L11-L12
This is, perhaps, the cause of the disappearance of the first commit. (Not sure whether it is at all possible to get at that commit now - would be interesting to explore).

Two worries! Sometimes files do land on two different dashboards. And remain finalizable for both users. Obviously the second user could have wondered at the comments, checked the live file and then decided to remove the file from his/her finalization section. This would have avoided the mess.

Second worry. First commit is irretrievable.

This is not particularly serious, because I am on top of it know what went wrong and can fix it. I would simply like confirmation of one or two oddities and weaknesses. Or am I just going quietly, or not so quietly bonkers? ;)

**Comment by jcowey** [comment]
A further oddity for me was that I went to repair the damage
http://papyri.info/ddbdp/sb;28;17015
open in editor
http://papyri.info/editor/publications/54128
where I was asked to create a new text, although there is one

**Comment by ryanfb** [comment]
So I see:

Board copy: 53966
James's copy: 53980, created: 2016-11-03 17:26:03, updated: 2016-11-04 15:12:04
Lajos's copy: 53992, created: 2016-11-04 12:14:04, updated: 2016-11-07 14:00:35
James's finalization commit: https://github.com/papyri/idp.data/commit/2b505f85ecca60c89ed0b7b31f691ca7e46a4aa5
Lajos's finalization commit: https://github.com/papyri/idp.data/commit/d5f3c6436a6814850047e93d70d9241ca392f99c

Note that all the commits are still there in the canonical Git history, but limitations of the (online) blame/history tool may not show you everything you want to see.

Based on the create/update timestamps, since the "updated" timestamp likely reflects the finalization time, I'm guessing that Lajos pressed "make me finalizer", for whatever reason James's copy wasn't deleted, James then several hours later finalized, and today Lajos finalized.  So, something messed up in make me finalizer for James's copy not to be deleted and still be finalizable. Unfortunately the (meaningful) logs were reset this morning so I can't trace back to see exactly what happened. The diff in [Lajos's finalization commit](https://github.com/papyri/idp.data/commit/d5f3c6436a6814850047e93d70d9241ca392f99c) should be what he saw in the finalization review page.

The reason you're asked to create a new text is because of the horked `sosol;2016;0826` identifier messing with the "open in editor" link on http://papyri.info/ddbdp/sb;28;17015. What you should do is **delete** the publication on your dashboard asking you to create a new text for SB 28 17015, and **then** click this link: http://papyri.info/editor/publications/create_from_identifier/papyri.info/ddbdp/sb;28;17015

**Comment by jcowey** [comment]
Thanks! How could I have accessed the "canonical Git history"?

**Comment by jcowey** [comment]
And if it is relatively easy for you to walk back to my commit 
https://github.com/papyri/idp.data/commit/2b505f85ecca60c89ed0b7b31f691ca7e46a4aa5
which is slightly better and what I would correct back to
would you please do so, as it would save me further contortions. If it is a pain then I can sort it all out myself.

**Comment by ryanfb** [comment]
If you go to https://github.com/papyri/idp.data/commits/master, or use `git log` locally in an up-to-date clone of idp.data, which is more easily searchable ("canonical Git history" just meant as master branch for idp.data vs. the blame/history for an individual file through the GitHub interface).

**Comment by jcowey** [comment]
https://github.com/papyri/idp.data/commits/master
Ah yes of course! Should have thought of that! Thanks. I shall know for another time to make that distinction.

**Comment by jcowey** [comment]
Gosh it has just happened again.
25 days ago I finalized SB 28 16870
https://github.com/papyri/idp.data/blob/1906590ca32571b8553d190475f0312d7c4d93c0/DDB_EpiDoc_XML/sb/sb.28/sb.28.16870.xml
today Josh voted on it
http://papyri.info/editor/publications/54137
I failed to be alert and finalized. I should have checked as I was a bit surprised to see it up for voting and finalization.
So that means that it remained stuck for Josh to vote on, although it was finalized over three weeks ago.

**Comment by ryanfb** [comment]
I think this is a different phenomenon. On this one I don't see two finalizers. I see an original publication (52978, created: 2016-09-14 14:42:04), one DDB board copy (54134, created: 2016-11-08 14:26:34), with one child (54137, created: 2016-11-08 16:58:51). The DDB copy has votes:
```
#<Vote id: 16511, choice: "AcceptText", user_id: 3, created_at: "2016-11-08 15:24:44", updated_at: "2016-11-08 15:24:44", publication_id: 54134, identifier_id: 123199, board_id: 1>, #<Vote id: 16515, choice: "AcceptText", user_id: 4, created_at: "2016-11-08 16:58:50", updated_at: "2016-11-08 16:58:50", publication_id: 54134, identifier_id: 123199, board_id: 1>
```
The original finalization merge is at: https://github.com/papyri/idp.data/commit/691dc338
The second finalization should be at: https://github.com/papyri/idp.data/commit/460e068f219c5b69d048447ad3022618aca1218e
 (once sync happens)

I think the problem here is: why was it possible to vote on this again? There is an associated translation publication as well, do we have a bug in our board workflow that caused this to go back to voting?

**Comment by jcowey** [comment]
I assume from the editorial history that there were two finalizers (on both occasions myself - all the more stupid that I did not notice at the time!!)
```

Editorial History; All History; (detailed)

    2016-11-08T12:16:52-05:00 [james.cowey]: Finalized - Ready.
    2016-11-08T11:58:50-05:00 [james.cowey]: Vote - AcceptText - See Sosin's comments.
    2016-11-08T10:24:44-05:00 [joshuad.sosin]: Vote - AcceptText - Accept. Lin1 <#κη=27#> ==> <#κη=28#> ; <#κ̣.1=20#> ==> <#κ̣̄.1=21-29#> ; lin2 ==> <#κη=28#> again ; lin3 ==> <:βασιλ[ί]σσης|reg|βασιλ[ί]σ̣η̣ς̣:> ; lin9 ==> <#κη=28#> again ; lin9 Ἐπεὶφ ==> Ἐπεὶ̣φ ; lin9 ==> <#[κ][.1]=21-29#>
    2016-11-08T09:26:34-05:00 [AliceMassimo]: Submit - insert the text following the edition
    2016-10-14T11:08:00-04:00 [james.cowey]: Finalized - Ready.
    2016-10-12T07:00:44-04:00 [james.cowey]: Vote - Accept-Straight-to-Finalization - Use small letters in lins1, 2 and 9
    2016-10-12T05:20:07-04:00 [AliceMassimo]: Submit - inserted text following the edition
    2016-09-14T10:42:39-04:00 [editor]: Automated creation from template
```
First one
```
2016-10-14T11:08:00-04:00 [james.cowey]: Finalized - Ready.
```
Second one
```

```

**Comment by ryanfb** [comment]
Yes, there were two finalizations. But not from the same board copy. So what happened for this one is that somehow, the original publication went back to the DDB board for voting again after it was finalized.

**Comment by jcowey** [comment]
OK. Still puzzling.

**Comment by ryanfb** [comment]
For this second one in the logs I see a second submit on the original publication that happened on 2016-11-08. This should only be possible in [`PublicationsController#submit`](https://github.com/sosol/sosol/blob/master/app/controllers/publications_controller.rb#L218) if the publication status is "editing" or "new". This publication has an associated translation, is it possible that the translation was rejected, causing it to go back to needing submission? I don't see any comments on the original publication before the second submission, which is also worrying/confounding.

**Comment by jcowey** [comment]
Checking on
http://papyri.info/editor/users/AliceMassimo
I can see only one submit
SB 28, 16870 (submitted)   insert the text following the edition November 08, 2016 14:26 
The appearance of the submit text
```
[AliceMassimo]: Submit - insert the text following the edition
```
twice in the editorial history for the text, quoted in the comment above, seems to indicate that there was only the ONE submit. I checked this, because I know that we sometimes get two submits of the same text from two different users.

**Comment by ryanfb** [comment]
The publication she submitted, though, was created 2016-09-14, originally submitted 2016-10-12 voted Accept STF the same day, then finalized 2016-10-14. The same publication was then submitted again 2016-11-08. The reason you only see the second submit on http://papyri.info/editor/users/AliceMassimo is because that uses the comments to display usage, and there are for whatever reason no comments associated with the publication from before the second submit. If the translation was returned to sender and that destroyed the comments (sosol/sosol#189), then that would explain what we saw with this publication.

**Comment by jcowey** [comment]
OK thanks for the explanation

**Comment by jcowey** [comment]
I think I have another example of similar behaviour. Esther Garel finalized O.Frange 776.
http://papyri.info/hgv/220314
Not sure what the ../editor/publications/ number of that file was, but here is the committed file:
https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/o.frange/o.frange.776.xml

Now on Esther Garel's dashboard in the Finalization section there is the file
http://papyri.info/editor/publications/54116
The file was entered by Korshi Dosoo. The notes are the same as the notes in the Editorial history of the finalized file
http://papyri.info/hgv/220314
which was likewise submitted by Korshi Dosoo.
It looks like a duplicate appeared somehow. I have asked Esther Garel to leave it on her dashboard, in the hope that you, Ryan, can perhaps maybe get more of an idea of what might have happened.
In the previous two cases I had ended up finalizing both files before realising what had happened. 
This case is not so far advanced.
Obviously I can ask Esther to "withdraw from editorial review" and the file will disappear. I hoped, however, that it might help you diagnose what is going on.

**Comment by ryanfb** [comment]
Yes, for some reason this case has 3 finalizing copies coming off the board copy (Mark Depauw also has one). So I'm not sure if these are occurring because of make-me-finalizer not successfully deleting the original finalizer's copy, or if something else is going on. In any case I'll try to work on it in sosol/sosol#190.
