### ISSUE TITLE
Renaming issue. Unclear about how to proceed.

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#8]
With reference to #7, Esther was able to make herself finalizer, but came across the following message when trying to rename: (this is a copy of her mail to me)

Good morning James,

Well, it seems this text has not finished causing difficulties... When I wanted to rename it before finalization, here is the error message I got (see the attachment): 

![ofrange356error](https://cloud.githubusercontent.com/assets/612992/13392692/a203f3e6-dedc-11e5-9349-5b0b52099689.png)

Hope it is just a tiny thing to fix !

Best,
Esther

Would you please let us know what to do in such a case. By the way this is a good place for us to start on this sort of problem, because I know that we have about another 7 cases where this sort of message is produced on renaming.

**Comment by ryanfb** [comment]
There's already an O.Frange 356 in canonical:

https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/o.frange/o.frange.356.xml

There are two HGV numbers associated with this:

* http://papyri.info/hgv/219895
* http://papyri.info/hgv/219896

It looks like what happened is HGV 219896 = 357 was already finalized as 356, or this publication (HGV 219895 = 356) is actually 357 and needs to be renamed to that instead. In either case I would suggest going ahead and renaming this to 357 (since that doesn't exist in canonical yet), and fixing the issue with re-submissions.

If this is actually 356 you can fix the issue by swapping the Leiden+ text between this and the already-finalized "356". If this is actually 357 you can fix the issue by swapping the HGV/TM idnos in the XML headers of both.

**Comment by jcowey** [comment]
Yes. I should really have figured this out myself. Thanks.
