### ISSUE TITLE
File causing problems on user's home dashboard

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#86]
The user
http://papyri.info/editor/users/Marja
has problems with the following publications number:

http://papyri.info/editor/publications/60113/

She cannot submit the file. She has saved and can continue to save and make changes but cannot submit. I had suggested that she delete the file, sign out and sign back in again and then try all over again.
She can, however, *not* delete the file.

Would you please try to unwedge the file so that she can submit.

**Comment by ryanfb** [comment]
This was hung seemingly because the publication copy-during-submit hung due to sosol/gitwrapper#5, so there was a lock held on the publication (for the submit) and no other actions could be performed with it. I manually submitted this publication and preserved the commit comment, but had to kill the `git ls-tree` process so it would fall back to the Git shell command for copying a publication. It seems to be in a good (submitted) state now.
